# Generated by Django 4.2.1 on 2023-06-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_side', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_list_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_charges_id', models.IntegerField(blank=True, null=True)),
                ('charges', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('rate', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cart_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemChargesView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_charges_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_image', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type_id', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charges', models.IntegerField(blank=True, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_for_id', models.IntegerField(blank=True, null=True)),
                ('service_for_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'item_charges_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemChargesView1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_charges_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_image', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type_id', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charges', models.IntegerField(blank=True, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_for_id', models.IntegerField(blank=True, null=True)),
                ('service_for_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'item_charges_view1',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemChargesView2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_charges_id', models.IntegerField(blank=True, null=True)),
                ('item_id', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=50, null=True)),
                ('item_image', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type_id', models.IntegerField(blank=True, null=True)),
                ('service_type', models.CharField(blank=True, max_length=50, null=True)),
                ('charges', models.IntegerField(blank=True, null=True)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('unit_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_for_id', models.IntegerField(blank=True, null=True)),
                ('service_for_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'item_charges_view2',
                'managed': False,
            },
        ),
    ]
